name: startup_generator
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  flutter_riverpod: ^0.14.0+3
  get_it: ^7.2.0
  cupertino_icons: ^1.0.2
  select_form_field: ^2.2.0
  fluttertoast: ^8.0.9
  dio: ^4.0.6
  firebase_core: ^1.17.1
  firebase_database: ^9.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
